name: nonprofit_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  home_widget: ^0.7.0
  youtube_player_flutter: ^9.1.1
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  flutter_contacts: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
